### ISSUE TITLE
Presentation

### ISSUE THREAD

**Issue by nanidam** [Medieinstitutet/fed22d-grafiska-verktyg-tomatsoppan#58]
Information om redovisningen:

•	10 min per grupp + 5 min teknikstrul
•	Testa teknik innan
•	Ska en person dra igenom redovisningen eller flera? Öva!
•	Tips: pecha kucha är ett bra redovisningsformat: 20 slides x 20 sekunder → 6 min 40 sekunder (fokus hålls uppe)

Frågeinspiration:
1.	Intressant att se hur man gjort med ramverk och liknande; om man testat något nytt och hur det kan se ut
2.	Hur kom ni fram till det arbetssätt som ni valde, och i efterhand, finns det något som ni skulle gjort annorlunda?
3.	Dela med er av ett kodproblem och hur ni löste det.
4.	Hur har man delat upp sitt arbete?
5.	Har gruppen jobbat förebyggande med pull requests/merges - har det funnits en plan eller har man bara kört?
6.	Hur folk började med att designa upp designen? Fanns det designbakgrund eller slängde ni er in i detta?
7.	Hur gick tankeprocessen för att ta fram design från start till mål?
8.	Hur har man jobbat på/med GitHub?
9.	Hur har ni hanterat oklarheter och svårigheter? Fokus på kod & design - om man är osäker på vad den andra gruppen gjort och hur man ska tolka det.
10.	Ett exempel på nåt ni trodde skulle bli lätt att lösa, men som blev komplext & bökigt!

**Comment by julia-lundbergish** [comment]
Fem slides per person enligt ordning:
1. Julia 
• Vår design (processen, designval, tidigare erfarenhet)
2. Sandra
• Designen vi tog emot (instruktioner vi fick från överlämningen, hur vi strukturerade upp arbetet utifrån det)
3. Björn
• Tekniker (vilka paket, tekniker, bibliotek vi arbetat med och hur)
4. Nani
• Grupparbetet (3 saker/tips vi tagit med oss, material från inspirationsfrågorna)
